# phonect-service.nix — NixOS module for the phonect unlock daemon (user service).
#
# Add this to your NixOS configuration:
#
#   imports = [ ./path/to/phonect-service.nix ];
#
#   services.phonect = {
#     enable = true;
#     settings = {
#       keys.public_key = "/home/zumuvik/.config/phonect/trusted_device.pub";
#       keys.private_key = "/home/zumuvik/.config/phonect/pc_private.pem";
#       device.bluetooth_mac = "AA:BB:CC:DD:EE:FF";
#       device.unlock_on_start = false;
#       device.pc_name = "my-laptop";
#       logging.level = "INFO";
#     };
#   };
#
# The generated config is written to `/etc/phonect/config.toml` and the daemon
# is started with `--config /etc/phonect/config.toml`.
#
# .. note:
#    No IP/host config needed.  The daemon uses Bluetooth RFCOMM to reach the
#    phone — pair the phone at the OS level first.
#
# The user service listens for resume-from-sleep events via D-Bus (logind
# PrepareForSleep on the *system* bus — accessible from user services).

{ config, lib, pkgs, ... }:

let
  cfg = config.services.phonect;

  phonectSrc = lib.cleanSourceWith {
    src = lib.cleanSource ./.;
    name = "phonect-source";
  };

  phonectPackage = pkgs.python3.pkgs.buildPythonPackage rec {
    pname = "phonect";
    version = "0.4.0";
    src = phonectSrc;
    pyproject = true;
    buildInputs = [ pkgs.python3.pkgs.setuptools ];
    propagatedBuildInputs = with pkgs.python3.pkgs; [
      cryptography
      dbus-next
      textual        # TUI (required — always included)
      qrcode         # TUI QR-code rendering
    ];
    doCheck = false;
  };

  # ── TOML config file generator ──────────────────────────────────────
  configFile = pkgs.writeText "phonect-config.toml" (
    let
      s = cfg.settings;
      inherit (lib) optionalString;
    in
    ''
      # phonect daemon configuration — generated by NixOS
      # Manual edits will be overwritten on rebuild.

      [keys]
      public_key = "${s.keys.public_key}"
      private_key = "${s.keys.private_key}"

      [device]
      bluetooth_mac = "${s.device.bluetooth_mac}"
      pc_name = "${s.device.pc_name}"
      unlock_on_start = ${if s.device.unlock_on_start then "true" else "false"}

      [logging]
      level = "${s.logging.level}"
    ''
  );

in {
  options.services.phonect = {
    enable = lib.mkEnableOption "phonect P2P biometric unlock daemon";

    package = lib.mkOption {
      type = lib.types.package;
      default = phonectPackage;
      defaultText = lib.literalExpression "phonect package with all extras";
      description = "The phonect Python package derivation.";
    };

    settings = lib.mkOption {
      description = "Configuration for phonect (maps to config.toml sections).";
      default = { };
      type = lib.types.submodule {
        options = {
          keys = {
            public_key = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Path to the trusted mobile device public key (PEM).";
            };
            private_key = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Path to the PC's own private key (PEM).";
            };
          };

          device = {
            bluetooth_mac = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Phone Bluetooth MAC address (XX:XX:XX:XX:XX:XX).";
            };
            pc_name = lib.mkOption {
              type = lib.types.str;
              default = "my-laptop";
              description = "Human-friendly PC name shown during pairing.";
            };
            unlock_on_start = lib.mkOption {
              type = lib.types.bool;
              default = false;
              description = "Run one auth cycle when the daemon starts.";
            };
          };

          logging = {
            level = lib.mkOption {
              type = lib.types.enum [ "DEBUG" "INFO" "WARNING" "ERROR" ];
              default = "INFO";
              description = "Log level for the daemon.";
            };
          };
        };
      };
    };
  };

  config = lib.mkIf cfg.enable {
    # ── Make the phonect CLI available in PATH ──────────────────────────
    environment.systemPackages = [ cfg.package ];

    # ── Config file (managed by NixOS) ──────────────────────────────────
    environment.etc."phonect/config.toml".source = configFile;

    # ── Ensure Bluetooth is available ──────────────────────────────────
    hardware.bluetooth.enable = lib.mkDefault true;

    # ── User service (runs on login, not as root) ───────────────────────
    systemd.user.services.phonect = {
      description = "phonect P2P Biometric Laptop Unlock Daemon";
      after = [
        "network.target"
        "bluetooth.target"
        "suspend.target"
        "hibernate.target"
        "hybrid-sleep.target"
      ];
      wants = [ "bluetooth.target" ];
      wantedBy = [ "default.target" ];
      partOf = [
        "suspend.target"
        "hibernate.target"
        "hybrid-sleep.target"
      ];
      before = [ "sleep.target" ];

      serviceConfig = {
        Type = "simple";
        ExecStart = "${cfg.package}/bin/phonect daemon --config /etc/phonect/config.toml";
        Restart = "on-failure";
        RestartSec = 5;

        # Lightweight hardening (compatible with user services)
        NoNewPrivileges = true;
        PrivateTmp = true;
        RestrictNamespaces = true;
        SystemCallArchitectures = "native";
        SystemCallFilter = [ "@system-service" ];
      };
    };
  };
}
