# phonect-service.nix — NixOS module for the phonect unlock daemon (user service).
#
# Add this to your NixOS configuration:
#
#   imports = [ ./path/to/phonect-service.nix ];
#
#   services.phonect = {
#     enable = true;
#     user = "my-user";
#     settings = {
#       keys.public_key = "/home/zumuvik/.config/phonect/trusted_device.pub";
#       keys.private_key = "/home/zumuvik/.config/phonect/pc_private.pem";
#       device.unlock_on_start = false;
#       device.pc_name = "my-laptop";
#       logging.level = "INFO";
#     };
#   };
#
# The generated config is written to `/etc/phonect/config.toml` and the daemon
# is started with `--config /etc/phonect/config.toml`.
#
# The daemon advertises over UDP discovery and listens for TCP connections from
# the Android app on the configured host/port.
#
# The user service listens for resume-from-sleep events via D-Bus (logind
# PrepareForSleep on the *system* bus — accessible from user services).

{ config, lib, pkgs, ... }:

let
  cfg = config.services.phonect;
  phonectPackage = pkgs.callPackage ./package.nix { };

  # ── TOML config file generator ──────────────────────────────────────
  configFile = pkgs.writeText "phonect-config.toml" (
    let
      s = cfg.settings;
    in
    ''
      # phonect daemon configuration — generated by NixOS
      # Manual edits will be overwritten on rebuild.

      [keys]
      public_key = "${s.keys.public_key}"
      private_key = "${s.keys.private_key}"

      [device]
      pc_name = "${s.device.pc_name}"
      unlock_on_start = ${if s.device.unlock_on_start then "true" else "false"}

      [daemon]
      listen_host = "${s.daemon.listen_host}"
      listen_port = ${toString s.daemon.listen_port}
      poll_interval = ${toString s.daemon.poll_interval}
      poll_timeout = ${toString s.daemon.poll_timeout}
      unlock_backend = "${s.daemon.unlock_backend}"
      unlock_command = ${builtins.toJSON s.daemon.unlock_command}

      [logging]
      level = "${s.logging.level}"
    ''
  );

in {
  options.services.phonect = {
    enable = lib.mkEnableOption "phonect P2P biometric unlock daemon";

    package = lib.mkOption {
      type = lib.types.package;
      default = phonectPackage;
      defaultText = lib.literalExpression "phonect package";
      description = "The phonect Python package derivation.";
    };

    user = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Normal user whose systemd user manager runs phonect.";
    };

    settings = lib.mkOption {
      description = "Configuration for phonect (maps to config.toml sections).";
      default = { };
      type = lib.types.submodule {
        options = {
          keys = {
            public_key = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Path to the trusted mobile device public key (PEM).";
            };
            private_key = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Path to the PC's own private key (PEM).";
            };
          };

          device = {
            pc_name = lib.mkOption {
              type = lib.types.str;
              default = "my-laptop";
              description = "Human-friendly PC name shown during pairing.";
            };
            unlock_on_start = lib.mkOption {
              type = lib.types.bool;
              default = false;
              description = "Run one auth cycle when the daemon starts.";
            };
          };

          daemon = {
            listen_host = lib.mkOption {
              type = lib.types.str;
              default = "0.0.0.0";
              description = "Address the daemon binds for TCP phone connections.";
            };
            listen_port = lib.mkOption {
              type = lib.types.port;
              default = 9876;
              description = "TCP port the daemon listens on.";
            };
            poll_interval = lib.mkOption {
              type = lib.types.float;
              default = 0.3;
              description = "Seconds between UDP discovery broadcasts during a bounded auth window.";
            };
            poll_timeout = lib.mkOption {
              type = lib.types.float;
              default = 15.0;
              description = "Seconds the daemon keeps each wake/manual auth window open.";
            };
            unlock_backend = lib.mkOption {
              type = lib.types.enum [ "loginctl" "command" ];
              default = "loginctl";
              description = "Local unlock backend.";
            };
            unlock_command = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
              description = "Static argv for the command unlock backend.";
            };
          };

          logging = {
            level = lib.mkOption {
              type = lib.types.enum [ "DEBUG" "INFO" "WARNING" "ERROR" ];
              default = "INFO";
              description = "Log level for the daemon.";
            };
          };
        };
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.user != null;
        message = "services.phonect.user must be configured when phonect is enabled.";
      }
      {
        assertion = cfg.user == null || builtins.hasAttr cfg.user config.users.users;
        message = "services.phonect.user must name a configured user.";
      }
      {
        assertion = cfg.user == null || !(builtins.hasAttr cfg.user config.users.users)
          || config.users.users.${cfg.user}.isNormalUser;
        message = "services.phonect.user must name a normal user.";
      }
      {
        assertion = cfg.settings.daemon.unlock_backend != "command"
          || (cfg.settings.daemon.unlock_command != [ ] && builtins.match "[[:space:]]*" (builtins.head cfg.settings.daemon.unlock_command) == null);
        message = "services.phonect.settings.daemon.unlock_command requires a nonblank executable for command.";
      }
      {
        assertion = cfg.settings.daemon.unlock_backend != "loginctl" || cfg.settings.daemon.unlock_command == [ ];
        message = "services.phonect.settings.daemon.unlock_command must be empty for loginctl.";
      }
    ];
    # ── Make the phonect CLI available in PATH ──────────────────────────
    environment.systemPackages = [ cfg.package ];

    # ── Config file (managed by NixOS) ──────────────────────────────────
    environment.etc."phonect/config.toml".source = configFile;

    # ── Open LAN discovery and daemon listener ports ───────────────────
    networking.firewall.allowedTCPPorts = [ cfg.settings.daemon.listen_port ];
    networking.firewall.allowedUDPPorts = [ 9875 ];

    # ── User service (runs on login, not as root) ───────────────────────
    systemd.user.services.phonect = {
      description = "phonect P2P Biometric Laptop Unlock Daemon";
      unitConfig.ConditionUser = cfg.user;
      after = [
        "network.target"
        "suspend.target"
        "hibernate.target"
        "hybrid-sleep.target"
      ];
      wantedBy = [ "default.target" ];
      partOf = [
        "suspend.target"
        "hibernate.target"
        "hybrid-sleep.target"
      ];
      before = [ "sleep.target" ];

      serviceConfig = {
        Type = "simple";
        ExecStart = "${cfg.package}/bin/phonect daemon --config /etc/phonect/config.toml";
        Restart = "on-failure";
        RestartSec = 5;

        # Lightweight hardening (compatible with user services)
        NoNewPrivileges = true;
        PrivateTmp = true;
        RestrictNamespaces = true;
        SystemCallArchitectures = "native";
        SystemCallFilter = [ "@system-service" ];
      };
    };
  };
}
