# phonect-service.nix — NixOS module for the phonect unlock daemon (user service).
#
# Add this to your NixOS configuration:
#
#   imports = [ ./path/to/phonect-service.nix ];
#
#   services.phonect = {
#     enable = true;
#     settings = {
#       device.mobile_ip = "192.168.1.100";
#       device.mobile_port = 9876;
#       keys.public_key = "/home/zumuvik/.config/phonect/trusted_device.pub";
#       keys.private_key = "/home/zumuvik/.config/phonect/pc_private.pem";
#       daemon.poll_interval_ms = 200;
#       daemon.poll_timeout_seconds = 10;
#       daemon.unlock_on_start = false;
#       daemon.pc_name = "my-laptop";
#       logging.level = "INFO";
#     };
#   };
#
# The generated config is written to `/etc/phonect/config.toml` and the daemon
# is started with `--config /etc/phonect/config.toml`.
#
# You can also set just `services.phonect.settings = { };` to use the defaults
# (you'll need to ensure key files exist at the default paths).
#
# The user service listens for resume-from-sleep events via D-Bus (logind
# PrepareForSleep on the *system* bus — accessible from user services).

{ config, lib, pkgs, ... }:

let
  cfg = config.services.phonect;

  phonectSrc = lib.cleanSourceWith {
    src = lib.cleanSource ./.;
    name = "phonect-source";
  };

  phonectPackage = pkgs.python3.pkgs.buildPythonPackage rec {
    pname = "phonect";
    version = "0.2.3";
    src = phonectSrc;
    pyproject = true;
    buildInputs = [ pkgs.python3.pkgs.setuptools ];
    propagatedBuildInputs = with pkgs.python3.pkgs; [
      cryptography
      dbus-next
      textual        # TUI (required — always included)
      qrcode         # TUI QR-code rendering
    ];
    doCheck = false;
  };

  # ── TOML config file generator ──────────────────────────────────────
  configFile = pkgs.writeText "phonect-config.toml" (
    let
      s = cfg.settings;
      inherit (lib) optionalString;
    in
    ''
      # phonect daemon configuration — generated by NixOS
      # Manual edits will be overwritten on rebuild.

      [device]
      mobile_ip = "${s.device.mobile_ip}"
      mobile_port = ${toString s.device.mobile_port}

      [keys]
      public_key = "${s.keys.public_key}"
      private_key = "${s.keys.private_key}"

      [daemon]
      poll_interval_ms = ${toString s.daemon.poll_interval_ms}
      poll_timeout_seconds = ${toString s.daemon.poll_timeout_seconds}
      unlock_on_start = ${if s.daemon.unlock_on_start then "true" else "false"}
      pc_name = "${s.daemon.pc_name}"

      [logging]
      level = "${s.logging.level}"
    ''
  );

in {
  options.services.phonect = {
    enable = lib.mkEnableOption "phonect P2P biometric unlock daemon";

    package = lib.mkOption {
      type = lib.types.package;
      default = phonectPackage;
      defaultText = lib.literalExpression "phonect package with all extras";
      description = "The phonect Python package derivation.";
    };

    settings = lib.mkOption {
      description = "Configuration for phonect (maps to config.toml sections).";
      default = { };
      type = lib.types.submodule {
        options = {
          device = {
            mobile_ip = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Static IP of the Android phone on your LAN.";
            };
            mobile_port = lib.mkOption {
              type = lib.types.port;
              default = 9876;
              description = "Port the phone's listener is bound to.";
            };
          };

          keys = {
            public_key = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Path to the trusted mobile device public key (PEM).";
            };
            private_key = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Path to the PC's own private key (PEM).";
            };
          };

          daemon = {
            poll_interval_ms = lib.mkOption {
              type = lib.types.ints.unsigned;
              default = 200;
              description = "How often (ms) to retry TCP connect during wakeup polling.";
            };
            poll_timeout_seconds = lib.mkOption {
              type = lib.types.ints.unsigned;
              default = 10;
              description = "Max polling window (seconds) before giving up.";
            };
            unlock_on_start = lib.mkOption {
              type = lib.types.bool;
              default = false;
              description = "Run one auth cycle when the daemon starts.";
            };
            pc_name = lib.mkOption {
              type = lib.types.str;
              default = "my-laptop";
              description = "Human-friendly PC name shown during pairing.";
            };
          };

          logging = {
            level = lib.mkOption {
              type = lib.types.enum [ "DEBUG" "INFO" "WARNING" "ERROR" ];
              default = "INFO";
              description = "Log level for the daemon.";
            };
          };
        };
      };
    };
  };

  config = lib.mkIf cfg.enable {
    # ── Make the phonect CLI available in PATH ──────────────────────────
    environment.systemPackages = [ cfg.package ];

    # ── Config file (managed by NixOS) ──────────────────────────────────
    environment.etc."phonect/config.toml".source = configFile;

    # ── User service (runs on login, not as root) ───────────────────────
    systemd.user.services.phonect = {
      description = "phonect P2P Biometric Laptop Unlock Daemon";
      after = [
        "network.target"
        "suspend.target"
        "hibernate.target"
        "hybrid-sleep.target"
      ];
      wantedBy = [ "default.target" ];
      partOf = [
        "suspend.target"
        "hibernate.target"
        "hybrid-sleep.target"
      ];
      before = [ "sleep.target" ];

      serviceConfig = {
        Type = "simple";
        ExecStart = "${cfg.package}/bin/phonect daemon --config /etc/phonect/config.toml";
        Restart = "on-failure";
        RestartSec = 5;

        # Lightweight hardening (compatible with user services)
        NoNewPrivileges = true;
        PrivateTmp = true;
        RestrictNamespaces = true;
        SystemCallArchitectures = "native";
        SystemCallFilter = [ "@system-service" ];
      };
    };
  };
}
