"""
phonect.tui — Textual-based TUI for phonect pairing, status, and logs.

Requires ``textual`` and ``qrcode`` (Pillow optional, pure-Python fallback).

Screens
-------
- **Pairing Wizard**: Generate PC keys, show ASCII QR code for phone scanning
- **Status**: Daemon running status, paired device info
- **Logs**: Real-time feed from ``journalctl --user -u phonect``
"""

from __future__ import annotations

import asyncio
import json
import os
import socket
import subprocess
from pathlib import Path
from typing import Optional

from textual import on
from textual.app import App, ComposeResult
from textual.containers import Horizontal
from textual.screen import Screen
from textual.widgets import (
    Button,
    Footer,
    Header,
    Input,
    Label,
    ListItem,
    ListView,
    RichLog,
    Static,
    TabbedContent,
    TabPane,
)

from phonect.config import (
    DaemonConfig,
    load_config,
    default_config_path,
)
from phonect.crypto import (
    generate_key_pair,
    fingerprint_from_public_key,
    public_key_to_pem,
    load_public_key,
    KeyPair,
)


# ======================================================================
# Constants
# ======================================================================

# Path where the NixOS module writes the daemon config
DAEMON_CONFIG_PATH = Path("/etc/phonect/config.toml")
# User-writable directory for keys generated by the TUI
USER_CONFIG_DIR: Path = (
    Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "phonect"
)


# ======================================================================
# Pairing token helpers
# ======================================================================


def make_pairing_token(
    pc_name: str,
    pc_ip: str,
    pc_port: int,
    pc_fingerprint: str,
    pc_public_key_pem: str,
) -> str:
    """Build a JSON token for QR-code pairing."""
    return json.dumps({
        "pc_name": pc_name,
        "pc_ip": pc_ip,
        "pc_port": pc_port,
        "pc_fingerprint": pc_fingerprint,
        "pc_public_key": pc_public_key_pem,
    }, separators=(",", ":"))


def render_ascii_qr(data: str) -> str:
    """Render a QR code as ASCII art (pure Python, no Pillow needed)."""
    import qrcode

    qr = qrcode.QRCode(
        version=None,          # auto-detect
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=2,
        border=2,
    )
    qr.add_data(data)
    qr.make(fit=True)

    # Convert matrix to ASCII
    try:
        matrix = qr.get_matrix()
        lines = []
        for row in matrix:
            line = "".join("  " if cell else "██" for cell in row)
            lines.append(line)
        return "\n".join(lines)
    except Exception:
        # Pure text fallback
        return qr.make_image().to_text(quiet_zone=2)


def discover_local_ip() -> str:
    """Heuristic: find the LAN IP by connecting to a non-routable address."""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.settimeout(0.5)
            s.connect(("192.168.1.1", 1))
            return s.getsockname()[0]
    except Exception:
        return "127.0.0.1"


# ======================================================================
# Helpers
# ======================================================================


def _load_daemon_config() -> DaemonConfig:
    """Load the config the daemon actually uses.

    Tries ``/etc/phonect/config.toml`` first (NixOS-generated), falls
    back to the default user path.
    """
    if DAEMON_CONFIG_PATH.exists():
        return load_config(DAEMON_CONFIG_PATH)
    return load_config()


# ======================================================================
# Pairing Wizard Screen
# ======================================================================


class PairingScreen(Screen):
    """Pairing wizard: generate PC keys, display QR code."""

    def compose(self) -> ComposeResult:
        yield Label("Pairing Wizard", classes="title")
        yield Label(
            "Generate a PC key pair and scan the QR code with the phonect Android app.",
            id="pairing-hint",
        )

        yield Label("PC Name:")
        yield Input(placeholder="my-laptop", id="pc-name")

        with Horizontal():
            yield Button("Generate PC Keys", id="btn-gen-keys", variant="primary")
            yield Button("Show QR Code", id="btn-show-qr", variant="default", disabled=True)

        yield Static("", id="key-status")
        yield Static("", id="pairing-qr", classes="qr-code")
        yield Button("Back", id="btn-back", variant="default")

    @on(Button.Pressed, "#btn-gen-keys")
    async def on_gen_keys(self) -> None:
        """Generate an RSA-4096 key pair in a background thread.

        RSA key generation is CPU-intensive (several seconds), so it runs
        in an executor to keep the UI responsive.
        """
        btn = self.query_one("#btn-gen-keys", Button)
        status = self.query_one("#key-status", Static)
        qr_btn = self.query_one("#btn-show-qr", Button)

        btn.disabled = True
        qr_btn.disabled = True
        status.update("[yellow]Generating RSA-4096 key pair…[/yellow]")

        try:
            # CPU-bound: run in thread executor
            loop = asyncio.get_running_loop()
            kp = await loop.run_in_executor(None, generate_key_pair)

            # Write keys to user-writable directory
            config_dir = USER_CONFIG_DIR
            config_dir.mkdir(parents=True, exist_ok=True)

            priv_path = config_dir / "pc_private.pem"
            pub_path = config_dir / "pc_public.pem"

            priv_path.write_bytes(kp.private_key_pem)
            pub_path.write_bytes(kp.public_key_pem)

            self._pc_kp = kp

            status.update(
                f"[green]✓[/green] Keys generated!\n"
                f"  Private: {priv_path} ({len(kp.private_key_pem)} bytes)\n"
                f"  Public:  {pub_path} ({len(kp.public_key_pem)} bytes)\n"
                f"  Fingerprint: {kp.public_key_fingerprint[:32]}…"
            )
            qr_btn.disabled = False
        except Exception as e:
            status.update(f"[red]Error generating keys: {e}[/red]")
            self.notify(f"Key generation failed: {e}", severity="error")
        finally:
            btn.disabled = False

    @on(Button.Pressed, "#btn-show-qr")
    def on_show_qr(self) -> None:
        """Show pairing QR code (synchronous — fast path)."""
        qr_widget = self.query_one("#pairing-qr", Static)

        if not hasattr(self, "_pc_kp"):
            # Try loading from files
            pub_path = USER_CONFIG_DIR / "pc_public.pem"
            if pub_path.exists():
                try:
                    pub = load_public_key(pub_path.read_bytes())
                    fp = fingerprint_from_public_key(pub)
                    pub_pem = public_key_to_pem(pub)

                    self._pc_kp = KeyPair(
                        private_key_pem=b"",
                        public_key_pem=pub_pem.encode(),
                        public_key_fingerprint=fp,
                    )
                except Exception as e:
                    qr_widget.update(f"[red]Error reading key: {e}[/red]")
                    self.notify(f"Cannot load public key: {e}", severity="error")
                    return
            else:
                qr_widget.update("[red]No keys found. Click 'Generate PC Keys' first.[/red]")
                return

        pc_name = self.query_one("#pc-name", Input).value or socket.gethostname()
        pc_ip = discover_local_ip()
        pc_port = 9876

        try:
            pairing_data = make_pairing_token(
                pc_name=pc_name,
                pc_ip=pc_ip,
                pc_port=pc_port,
                pc_fingerprint=self._pc_kp.public_key_fingerprint,
                pc_public_key_pem=self._pc_kp.public_key_pem.decode(),
            )

            qr_art = render_ascii_qr(pairing_data)

            info = (
                f"\n[b]PC Name:[/b] {pc_name}\n"
                f"[b]IP:[/b] {pc_ip}:{pc_port}\n"
                f"[b]Fingerprint:[/b] {self._pc_kp.public_key_fingerprint[:32]}…\n"
                f"\nScan this QR code with the phonect Android app:\n"
            )
            qr_widget.update(info + qr_art)
        except Exception as e:
            qr_widget.update(f"[red]Error generating QR code: {e}[/red]")
            self.notify(f"QR generation failed: {e}", severity="error")

    @on(Button.Pressed, "#btn-back")
    def on_back(self) -> None:
        self.app.pop_screen()


# ======================================================================
# Status Screen
# ======================================================================


class StatusScreen(Screen):
    """Display daemon status and paired devices."""

    def compose(self) -> ComposeResult:
        yield Label("Daemon Status", classes="title")
        yield Static("", id="status-config")
        yield Static("", id="status-keys")
        yield ListView(id="paired-list")
        yield Button("Refresh", id="btn-refresh", variant="default")
        yield Button("Back", id="btn-back")

    def on_mount(self) -> None:
        self.refresh_status()

    @on(Button.Pressed, "#btn-refresh")
    def refresh_status(self) -> None:
        """Load status from the daemon's actual config path."""
        try:
            config = _load_daemon_config()
        except Exception as e:
            self.query_one("#status-config", Static).update(
                f"[red]Error loading config: {e}[/red]"
            )
            self.notify(f"Config load failed: {e}", severity="error")
            return

        config_source = (
            DAEMON_CONFIG_PATH if DAEMON_CONFIG_PATH.exists() else default_config_path()
        )

        config_status = (
            f"[b]Config:[/b] {config_source}\n"
            f"[b]Mobile IP:[/b] {config.mobile_ip or '(not set)'}\n"
            f"[b]Mobile Port:[/b] {config.mobile_port}\n"
            f"[b]PC Name:[/b] {config.pc_name or socket.gethostname()}\n"
        )
        self.query_one("#status-config", Static).update(config_status)

        try:
            pub_ok = config.public_key_path.exists()
            priv_ok = config.private_key_path.exists()
        except Exception:
            pub_ok = priv_ok = False

        key_status = (
            f"[b]Mobile pubkey:[/b] {'✓' if pub_ok else '✗'} "
            f"{config.public_key_path}\n"
            f"[b]PC privkey:[/b]   {'✓' if priv_ok else '✗'} "
            f"{config.private_key_path}\n"
            f"[b]Mutual auth:[/b]  {'✓ READY' if config.mutual_auth_ready else '— not configured'}\n"
        )
        self.query_one("#status-keys", Static).update(key_status)

        # Show paired device from config
        paired_list = self.query_one("#paired-list", ListView)
        paired_list.clear()
        if pub_ok:
            try:
                pub = load_public_key(config.public_key_path.read_bytes())
                fp = fingerprint_from_public_key(pub)
                paired_list.append(ListItem(Label(
                    f"IP: {config.mobile_ip}:{config.mobile_port}  "
                    f"FP: {fp[:16]}…"
                )))
            except Exception as e:
                paired_list.append(ListItem(Label(f"[red]Error reading key: {e}[/red]")))
        else:
            paired_list.append(ListItem(Label("No devices paired yet")))

    @on(Button.Pressed, "#btn-back")
    def on_back(self) -> None:
        self.app.pop_screen()


# ======================================================================
# Logs Screen
# ======================================================================


class LogsScreen(Screen):
    """Real-time journalctl log viewer for phonect daemon.

    Uses ``journalctl --user -n 50 -f -u phonect`` to tail logs from the
    user-systemd service.  The subprocess is driven through
    ``asyncio.create_subprocess_exec`` so the main event loop never blocks.
    """

    def compose(self) -> ComposeResult:
        yield Label("Daemon Logs", classes="title")
        yield RichLog(id="log-view", highlight=True, markup=True, max_lines=500)
        yield Horizontal(
            Button("Pause", id="btn-pause"),
            Button("Clear", id="btn-clear"),
            Button("Back", id="btn-back"),
        )

    def on_mount(self) -> None:
        self._log_view = self.query_one("#log-view", RichLog)
        self._paused = False
        self._log_view.write("[dim]Connecting to journalctl…[/dim]")
        self._tail_task = asyncio.create_task(self._tail_journalctl())

    async def _tail_journalctl(self) -> None:
        """Tail ``journalctl --user -n 50 -f -u phonect`` asynchronously.

        The subprocess is created with ``asyncio.create_subprocess_exec``
        so reading stdout never blocks the UI thread.  All errors are
        caught and displayed inline (with a ``self.app.notify()`` banner).
        """
        try:
            proc = await asyncio.create_subprocess_exec(
                "journalctl",
                "--user",
                "-n", "50",
                "-f",
                "-u", "phonect",
                "--no-pager",
                "--output=short-iso",
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
        except FileNotFoundError:
            msg = "[yellow]journalctl not available (not Linux/systemd)[/yellow]"
            self._log_view.write(msg)
            self.notify("journalctl not found — not running on Linux/systemd?", severity="error")
            return
        except Exception as e:
            msg = f"[red]Failed to start journalctl: {e}[/red]"
            self._log_view.write(msg)
            self.notify(f"journalctl error: {e}", severity="error")
            return

        self._log_view.write("[green]✓[/green] Connected, waiting for logs…")
        self._log_view.clear()

        # Read loop — asyncio buffered IO, never blocks
        while True:
            try:
                line = await asyncio.wait_for(proc.stdout.readline(), timeout=30.0)
            except asyncio.TimeoutError:
                # No output for 30s — not an error, just keep waiting
                continue
            except Exception as e:
                self._log_view.write(f"[red]Log read error: {e}[/red]")
                self.notify(f"Log stream error: {e}", severity="error")
                break

            if not line:
                # EOF — journalctl exited
                break

            if not self._paused:
                try:
                    self._log_view.write(line.decode("utf-8", errors="replace").rstrip())
                except Exception as e:
                    self._log_view.write(f"[red]Log decode error: {e}[/red]")

        # If we get here the subprocess ended
        self._log_view.write("[dim]journalctl process ended[/dim]")

    @on(Button.Pressed, "#btn-pause")
    def on_pause(self) -> None:
        self._paused = not self._paused
        btn = self.query_one("#btn-pause", Button)
        btn.label = "Resume" if self._paused else "Pause"

    @on(Button.Pressed, "#btn-clear")
    def on_clear(self) -> None:
        self._log_view.clear()

    @on(Button.Pressed, "#btn-back")
    def on_back(self) -> None:
        self._tail_task.cancel()
        self.app.pop_screen()


# ======================================================================
# Main TUI Application
# ======================================================================


class PhonectTui(App):
    """Textual TUI for phonect configuration and pairing."""

    CSS = """
    Screen {
        align: center top;
    }

    .title {
        text-style: bold;
        content-align: center top;
        padding: 1;
        background: $accent;
        color: $text;
    }

    .qr-code {
        margin: 1 2;
        padding: 1;
        border: solid $primary;
        min-height: 10;
    }

    #pairing-hint {
        padding: 0 2;
        color: $text-muted;
    }

    Button {
        margin: 0 1;
    }

    #btn-gen-keys, #btn-show-qr, #btn-refresh {
        min-width: 24;
    }

    #key-status {
        padding: 1 2;
    }

    RichLog {
        border: solid $primary;
        height: 80%;
        margin: 1 0;
    }
    """

    def compose(self) -> ComposeResult:
        yield Header(show_clock=True)
        with TabbedContent(initial="pairing"):
            with TabPane("Pairing", id="pairing"):
                yield PairingScreen()
            with TabPane("Status", id="status"):
                yield StatusScreen()
            with TabPane("Logs", id="logs"):
                yield LogsScreen()
        yield Footer()


def run_tui() -> None:
    """Entry point for ``phonect tui``."""
    app = PhonectTui()
    app.run()


if __name__ == "__main__":
    run_tui()
